#!/bin/bash
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2014 Volker Theile
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

count=$(omv_config_get_count "//services/remoteshare/nfsshares/nfsshare");

# remote nfs share entries
index=0;
while [ ${index} -le ${count} ]; do
    enable=$(omv_config_get "//services/remoteshare/nfsshares/nfsshare[position()=${index}]/enable")
    entry=$(omv_config_get "//services/remoteshare/nfsshares/nfsshare[position()=${index}]/fstab_line")
    if [ "${enable}" != "0" -a "${entry}" != "" ]; then
        echo ${entry}
    fi
    index=$(( ${index} + 1 ))
done;

count=$(omv_config_get_count "//services/remoteshare/smbshares/smbshare");

# remote samba share entries
index=0;
while [ ${index} -le ${count} ]; do
    enable=$(omv_config_get "//services/remoteshare/smbshares/smbshare[position()=${index}]/enable")
    entry=$(omv_config_get "//services/remoteshare/smbshares/smbshare[position()=${index}]/fstab_line")
    if [ "${enable}" != "0" -a "${entry}" != "" ]; then
        echo ${entry}
    fi
    index=$(( ${index} + 1 ))
done;

count=$(omv_config_get_count "//services/remoteshare/webdavshares/webdavshare");

# remote WebDAV share entries
index=0;
while [ ${index} -le ${count} ]; do
    enable=$(omv_config_get "//services/remoteshare/webdavshares/webdavshare[position()=${index}]/enable")
    entry=$(omv_config_get "//services/remoteshare/webdavshares/webdavshare[position()=${index}]/fstab_line")
    if [ "${enable}" != "0" -a "${entry}" != "" ]; then
        echo ${entry}
    fi
    index=$(( ${index} + 1 ))
done;
