#!/bin/bash
#
# Copyright (C) 2013-2014 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

CRED_FILE="/root/.smbcredentials-"

count=$(omv_config_get_count "//services/remoteshare/smbshares/smbshare");

# remote samba share entries
index=1;
while [ ${index} -le ${count} ]; do
    credfile=$(omv_config_get "//services/remoteshare/smbshares/smbshare[position()=${index}]/usefile")
    sfref=$(omv_config_get "//services/remoteshare/smbshares/smbshare[position()=${index}]/sharedfolderref")
    username=$(omv_config_get "//services/remoteshare/smbshares/smbshare[position()=${index}]/username")
    password=$(omv_config_get "//services/remoteshare/smbshares/smbshare[position()=${index}]/password")
    
    if [ "${credfile}" != "0" ]; then
        echo "username=${username}" > ${CRED_FILE}${sfref}
        echo "password=${password}" >> ${CRED_FILE}${sfref}
    fi
    
    index=$(( ${index} + 1 ))
done;

omv-mkconf fstab
mount -a
