#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
configure)

    if ! omv_config_exists "/config/services/remoteshare"; then
        echo "Initial configuration."
        object="<nfsshares></nfsshares>"
        object="${object}<smbshares></smbshares>"
        omv_config_add_element "/config/services" "remoteshare" "${object}" true
    fi
    ;;

abort-upgrade|abort-remove|abort-deconfigure)
    ;;

*)
    echo "postinst called with unknown argument" >&2
    exit 1
    ;;

esac

exit 0
