#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SERVICE_XPATH_NAME="remoteshare"
SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

case "$1" in
    configure)

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            echo "Initial configuration."
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/nfsshares"; then
            omv_config_add_element "${SERVICE_XPATH}" "nfsshares" ""
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/smbshares"; then
            omv_config_add_element "${SERVICE_XPATH}" "smbshares" ""
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/webdavshares"; then
            omv_config_add_element "${SERVICE_XPATH}" "webdavshares" ""
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/glustershares"; then
            omv_config_add_element "${SERVICE_XPATH}" "glustershares" ""
        fi

        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0
